# Generated by Django 5.2.4 on 2025-07-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimePunchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('punch_count', models.IntegerField()),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('punch_date', models.DateField()),
                ('punch_hour', models.TimeField()),
                ('employee_number', models.IntegerField()),
                ('time_punch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_punches', to='shifts.timepunchfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
