# Generated by Django 5.2.4 on 2025-07-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepunchfile',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='timepunchfile',
            name='status',
            field=models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('in_progress', 'Em andamento')], default='in_progress', max_length=45),
        ),
        migrations.AlterField(
            model_name='timepunchfile',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='timepunchfile',
            name='punch_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
